### ISSUE TITLE
php 8 support

### ISSUE THREAD

**Issue by Qetbn** [retailcrm/api-client-php#104]
Looks like dependencies don't support php8.

./composer.json has been updated
Running composer update symfony/http-client guzzlehttp/psr7 retailcrm/api-client-php
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - retailcrm/api-client-php[dev-master, v6.0.0, ..., v6.0.2] require liip/serializer ^2.0 -> satisfiable by liip/serializer[2.0.0, ..., 2.x-dev (alias of dev-master)].
    - liip/serializer 2.x-dev is an alias of liip/serializer dev-master and thus requires it to be installed too.
    - liip/serializer[dev-master, 2.0.0, ..., 2.0.3] require php ^7.2 -> your php version (8.0.7) does not satisfy that requirement.
    - retailcrm/api-client-php 6.x-dev is an alias of retailcrm/api-client-php dev-master and thus requires it to be installed too.
    - Root composer.json requires retailcrm/api-client-php ~6.0 -> satisfiable by retailcrm/api-client-php[v6.0.0, v6.0.1, v6.0.2, 6.x-dev (alias of dev-master)].

**Comment by gwinn** [comment]
yeap, it will support php 8 later, subscribe for updates
