### ISSUE TITLE
Civi\CompilePlugin\Util\ComposerPassthru

### ISSUE THREAD

**Issue by it59com** [retailcrm/api-client-php#112]
Install 
PHP 8.0.9 windows x64
ComposerPassthru.php on line 62
PHP Fatal error:  Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in

implode(' ', $this->options)
to
($this->options) ? implode(' ', $this->options) : null ,

**Comment by Neur0toxine** [comment]
Hello. Please report this to https://github.com/civicrm/composer-compile-plugin/issues/new.
