### ISSUE TITLE
API version needs to be updated

### ISSUE THREAD

**Issue by jurchiks** [retailcrm/api-client-php#16]
https://github.com/retailcrm/api-client-php/blob/master/lib/RetailCrm/ApiClient.php#L34
This library still uses v3 of the API, but the documentation says to use v4:
http://www.retailcrm.ru/docs/Developers/ApiRules

> При работе с API необходимо использовать версию v4.

**Comment by muxx** [comment]
Yes. New version of the PHP api client will appear soon. The near one-two weeks.

**Comment by jurchiks** [comment]
@muxx well, how's the progress?

**Comment by jurchiks** [comment]
@muxx any news?

**Comment by muxx** [comment]
Hi, new version in branch `v4`. It will be merged to master at the next week.

**Comment by jurchiks** [comment]
Alright, thanks!

**Comment by gwinn** [comment]
v4 merged at master

**Comment by jurchiks** [comment]
Alright, thanks!
