### ISSUE TITLE
Wrong type of "success" param in response

### ISSUE THREAD

**Issue by Lexa-san** [retailcrm/api-client-php#33]
Sometimes Response object has string values in bool parameters.

E.g. in good conditions when I try to get order list by URL like
`https://demo.retailcrm.ru/api/v4/orders?apiKey=..`.
I see in JSON  in _response_ object _success_ parameter with value true (type is bool):
```
{
...
    "success": true
...
}
```

But when something is wrong (just lost one symbol from account name)
`https://dem.retailcrm.ru/api/v4/orders?apiKey=..`
in JSON I see string value "false" of _success_ parameter:
```
{
    "errorMsg": "Account does not exist.",
    "success": "false"
}
```
In bad way `ApiResponse::getSuccess()` works wrong.

**Comment by muxx** [comment]
This is not api client error thats why i close this issue. But thanks, we will fix this bug.
