### ISSUE TITLE
New API v5 is not worked

### ISSUE THREAD

**Issue by XOlegator** [retailcrm/api-client-php#43]
Current version of library (v5.0.1) is not worked with API v5 methods (only API v4). Code for test - https://gist.github.com/XOlegator/2114ec1bd4d3cdbcfcf98f3b7e00073c
It give this result:
```
Версия = v4
RetailCrm\Response\ApiResponse Object
(
    [statusCode:protected] => 400
    [response:protected] => Array
        (
            [success] => 
            [errorMsg] => Order already exists.
        )

)
Версия = v5
RetailCrm\Response\ApiResponse Object
(
    [statusCode:protected] => 404
    [response:protected] => Array
        (
            [success] => 
            [errorMsg] => API method not found
        )

)
```

**"API method not found"** - this is for v5 only!

**Comment by muxx** [comment]
It meens that you test an account on version 5. You should update your account to version 6.
