### ISSUE TITLE
Bug in customFields methods

### ISSUE THREAD

**Issue by XOlegator** [retailcrm/api-client-php#47]
There are customFieldsCreate(), customFieldsEdit and customFieldsGet() methods has buggy check:
`if (empty($entity) || $entity != 'customer' || $entity != 'order')`
They are always return true. It can be improve fore example by this code:
`if (empty($entity) || !in_array($entity, ['customer', 'order']))`

**Comment by gwinn** [comment]
[fixed](https://github.com/retailcrm/api-client-php/commit/3dd663e7a640281afcd77f7307fc907a19cb2e64)
