### ISSUE TITLE
Предлагаю создать метод getClient() в AbstractLoader

### ISSUE THREAD

**Issue by Carsak** [retailcrm/api-client-php#52]
Как сейчас:
Есть класс AbstractLoader с закрытым свойством $client. Из этого, нельзя вызвать кастомный метод в АПИ. Например, сейчас не реализован метод /api/v5/store/products.
Сейчас приходится создавать свой класс, который расширяет  класс \RetailCrm\Http\Client, чтобы вызвать вот такой код
```php
class MyCustomClient extends \RetailCrm\Http\Client
.....................................
$client = new MyCustomClient();
$client->makeRequest('/store/products', 'GET', $params);
```

Как можно:
создать метод getClient() в \RetailCrm\Client\AbstractLoader, который возвращает $client
тогда можно сделать так
```php
$response = $client->request->getClient()->makeRequest('/store/products', 'GET', $params);
```
Исчезнеть ошибка при вызове

```php
$response = $client->request->client->makeRequest('/store/products', 'GET', $params);

Cannot access protected property RetailCrm\Client\ApiVersion5::$client
```
![image](https://user-images.githubusercontent.com/9497934/33559378-c10d1e92-d936-11e7-9e05-f3667ba38b99.png)

**Comment by gwinn** [comment]
> сейчас не реализован метод /api/v5/store/products.

Реализован. обратите внимание, что v5 использует трейты из v4

**Comment by Carsak** [comment]
Спасибо метод нашел.
Странно, что ПХПшторм не может его найти. Видит в request-e api 3-ю версию, хотя там 5 версия
![image](https://user-images.githubusercontent.com/9497934/33614846-a1f84b68-da02-11e7-867c-33c80380dc20.png)

phpStorm version 2017.3
