### ISSUE TITLE
Не хватает метода добавления товара к заказу

### ISSUE THREAD

**Issue by Carsak** [retailcrm/api-client-php#53]
В данный момент нет возможности добавить товар к закзазу.

Как я понял торговое предложение(offer), которое упоминается в документации это совсем иное, другая сущность нежели продукт
https://www.retailcrm.ru/docs/Developers/ApiVersion5#post--api-v5-orders-create.

Нельзя воспроизвести добавление товара через АПИ
![image](https://user-images.githubusercontent.com/9497934/33616922-8dc220d2-da08-11e7-91a9-440b5eeab925.png)
Доступ к методу divide-discount, который добавляет, удаляет товары, закрыт

![image](https://user-images.githubusercontent.com/9497934/33617040-e2e56308-da08-11e7-84a4-8828c242feaf.png)

**Comment by muxx** [comment]
Коллега, просьба в данном репозитории заводить тикеты только по самому api-клиенту для PHP. Все вопросы по работе с интерфейсом или API retailCRM просьба писать в техподдержку http://www.retailcrm.ru/contacts

**Comment by Carsak** [comment]
Да, согласен. Можно ли удалить этот issue?

**Comment by muxx** [comment]
Если вы заметили, я его уже закрыл
