### ISSUE TITLE
Нужна подсказка)

### ISSUE THREAD

**Issue by vasakapla** [retailcrm/api-client-php#77]
Есть более понятная инструкция для работы с библиотекой? Глобальная цель это оптимизировать скорость работы моей статистики(подгружаю много данных но делаю это через file_get_content и получается очень много запросов, а multi curl даже 2 запроса в секунду выдает ошибку типо много запросов делаю), работаю через file_get_content так как не смог разобраться с библиотекой(( В поддержку не пишу так как долго очень отвечают

**Comment by gwinn** [comment]
Что именно вызывает сложность?
