### ISSUE TITLE
Пользовательский заголовок в запрос

### ISSUE THREAD

**Issue by ipolikarpov** [retailcrm/api-client-php#82]
Доброго дня!
Верно ли я понял, что добавить свой заголовок к curl-запросу нельзя?

**Comment by gwinn** [comment]
О каком заголовке речь?

**Comment by ipolikarpov** [comment]
например,
`curl_setopt($curlHandler, CURLOPT_HTTPHEADER, array('X-Rlimit-token: ****'));`

**Comment by gwinn** [comment]
В данный момент нет, а можете подробнее рассказать про кейс, когда вам нужно установить такой заголовок?

**Comment by muxx** [comment]
@gwinn это для специально выделенных повышенных лимитов

**Comment by ipolikarpov** [comment]
> В данный момент нет, а можете подробнее рассказать про кейс, когда вам нужно установить такой заголовок?

В отдельных случаях ТП выдает такого рода заголовок для повышения лимитов обращений к API.
Я пока в проекте хардкорно в Client.php добил его, вот пытаюсь разобраться как грамотно его вам предложить для внесения в проект.

**Comment by muxx** [comment]
Токен типовой с точки зрения именования. Думаю имеет смысл завести отдельный атрибут класса с геттером/сеттером

**Comment by ipolikarpov** [comment]
Типа
`$client->setCustomHeader(''X-Rlimit-token: ****'')`
?

**Comment by ipolikarpov** [comment]
> Типа
> `$client->setCustomHeader(''X-Rlimit-token: ****'')`
> ?

Тут даже правильнее будет массив передавать
`$client->setCustomHeader(array('X-Rlimit-token: ****'));`

**Comment by muxx** [comment]
Нет, типа
```php
$client->setLimitToken('23f23...');
$client->getLimitToken();
```

Соответственно приватный атрибут класса ```$limitToken``` и его подстановка в заголовки, если есть.
