### ISSUE TITLE
Фатальная ошибка при использовании библиотеки

### ISSUE THREAD

**Issue by Zorgios** [retailcrm/api-client-php#87]
Импортировал вашу библиотеку в папку с проектом. Пытаюсь вызвать для тестов метод получения информации о заказе. Получаю ошибку:
PHP Fatal error:  Uncaught Error: Class 'RetailCrm\\ApiClient' not found in public_html/test/test.php:2\nStack trace:\n#0 {main}\n  thrown in public_html/test/test.php on line 2

Все файлы библиотеки лежат по пути public_html/test

**Comment by gwinn** [comment]
А каким именно образом производился импорт? Какая версия PHP и composer используются в Вашем проетке?

**Comment by Zorgios** [comment]
> А каким именно образом производился импорт? Какая версия PHP и composer используются в Вашем проетке?

PHP 7.1
Composer 1.10.10
Импорт производился согласно инструкции на github

**Comment by gwinn** [comment]
а можете сбросить тот фрагмент кода где Вы производите импорт библиотеки?

**Comment by Zorgios** [comment]
> а можете сбросить тот фрагмент кода где Вы производите импорт библиотеки?

Импорт - в плане первоначальной установки библиотеки или уже при использовании?

**Comment by gwinn** [comment]
При использовании
