### ISSUE TITLE
Каким образом получить список расходов?

### ISSUE THREAD

**Issue by Zorgios** [retailcrm/api-client-php#90]
Как получить список расходов? Пытаюсь вызвать метод costsList - ошибка с обработкой ответа.

require 'vendor/autoload.php';

$client = new \RetailCrm\ApiClient(
    'domen',
    'key',
    \RetailCrm\ApiClient::V5
);

try {
    $response = $client->request->costsList;
} catch (\RetailCrm\Exception\CurlException $e) {
    echo "Connection error: " . $e->getMessage();
}

if ($response->isSuccessful()) {
    echo $response;
} else {
    echo sprintf(
        "Error: [HTTP-code %s] %s",
        $response->getStatusCode(),
        $response->getErrorMsg()
    );
}

**Comment by Neur0toxine** [comment]
Добрый вечер!

В предоставленном сниппете присутствуют две ошибки. В строке
```php
$response = $client->request->costsList;
```
идёт обращение к методу класса как к свойству.
В строке
```php
echo $response;
```
производится попытка вывода `$response` как строки, но в `$response` находится экземпляр `RetailCrm\Response\ApiResponse`, его нельзя как строку вывести.
