### ISSUE TITLE
Некорректно работает метод редактирования информации о файле.

### ISSUE THREAD

**Issue by Zorgios** [retailcrm/api-client-php#91]
Некорректно работает редактирование информации о файле.
fileEdit($file) он же  /api/v5/files/{id}/edit

В ответе возвращается положительный результат, хотя файл не прикрепляется.

Информация подтверждена технической поддержкой RetailCRM.

**Comment by iyzoer** [comment]
Перепроверили метод, никаких ошибок не нашли, файлы прикрепляются корректно. Перепроверьте ваш запрос
Рабочий для примера:
```php
$client = new \RetailCrm\ApiClient(
    'https://xxx.retailcrm.ru',
    'XXX',
    \RetailCrm\ApiClient::V5
);

$file = [
    'filename' => 'Test file',
    'id' => 1,
    'attachment' => [
        [
            'customer' => [
                'id' => 1
            ],
            'order' => [
                'id' => 1
            ]
        ]
    ]
];

$client->request->fileEdit($file);
```

**Comment by gwinn** [comment]
#92 внедрено улучшение привносящее более прозрачную логику использования
